// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://chaeovusyrwmevptiesg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoYWVvdnVzeXJ3bWV2cHRpZXNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MjEwODYsImV4cCI6MjA2NDk5NzA4Nn0.Dzi_NFZa4PJj-1bSxrfkvAicyVMXK4-ZwqYjWB3lH3E";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);